CREATE TABLE [dbo].[mfBranchMaster](
	[Branch_ID] [int] IDENTITY(1,1) NOT NULL,
	[BranchName] [varchar](max) NULL,
 CONSTRAINT [PK_mfBranchMaster] PRIMARY KEY CLUSTERED 
(
	[Branch_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User_Type_Indication]    Script Date: 19-01-2026 13:31:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO